//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GW2PAO.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GW2PAO.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   About과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   active for과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ActiveFor {
            get {
                return ResourceManager.GetString("ActiveFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   active in과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ActiveIn {
            get {
                return ResourceManager.GetString("ActiveIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add New Task과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AddNewTask {
            get {
                return ResourceManager.GetString("AddNewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adjusted과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Adjusted {
            get {
                return ResourceManager.GetString("Adjusted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GW2 Personal Assistant Overlay과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto-Detect Completion과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AutoComplete {
            get {
                return ResourceManager.GetString("AutoComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto-Complete Based on Location과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AutoCompleteTasks {
            get {
                return ResourceManager.GetString("AutoCompleteTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto-Fade Window Borders과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AutoFadeBorders {
            get {
                return ResourceManager.GetString("AutoFadeBorders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto-Hide All Windows when GW2 is not running과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AutoHideAllWindowsGW2Closed {
            get {
                return ResourceManager.GetString("AutoHideAllWindowsGW2Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto-Hide All Windows when GW2 loses focus과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AutoHideAllWindowsGW2LoseFocus {
            get {
                return ResourceManager.GetString("AutoHideAllWindowsGW2LoseFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto-Hide Border과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AutoHideBorder {
            get {
                return ResourceManager.GetString("AutoHideBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto-Hide Overlay Menu Icon when GW2 loses focus과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AutoHideOverlayIconGW2LoseFocus {
            get {
                return ResourceManager.GetString("AutoHideOverlayIconGW2LoseFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto-Hide Overlay Menu Icon when GW2 is not running과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AutoHideOverlayIconWhenGW2NotRunning {
            get {
                return ResourceManager.GetString("AutoHideOverlayIconWhenGW2NotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automatic Unlock과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AutomaticUnlock {
            get {
                return ResourceManager.GetString("AutomaticUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automatically open and close tracker when entering/exiting WvW과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AutoOpenCloseWvW {
            get {
                return ResourceManager.GetString("AutoOpenCloseWvW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto-Start과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AutoStart {
            get {
                return ResourceManager.GetString("AutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto-Stop과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AutoStop {
            get {
                return ResourceManager.GetString("AutoStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Average Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AverageTime {
            get {
                return ResourceManager.GetString("AverageTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Based on Buy Order Price과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BasedOnBuyOrder {
            get {
                return ResourceManager.GetString("BasedOnBuyOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Based on Sell Listing Price과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BasedOnSellListing {
            get {
                return ResourceManager.GetString("BasedOnSellListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Best Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BestTime {
            get {
                return ResourceManager.GetString("BestTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Best Times과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BestTimes {
            get {
                return ResourceManager.GetString("BestTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bloodlust Objectives과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BloodlustObjectives {
            get {
                return ResourceManager.GetString("BloodlustObjectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blue Borderlands과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BlueBorderlands {
            get {
                return ResourceManager.GetString("BlueBorderlands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blue Objectives과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BlueObjectives {
            get {
                return ResourceManager.GetString("BlueObjectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Break Even At:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BreakEven {
            get {
                return ResourceManager.GetString("BreakEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Buy Order과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BuyOrder {
            get {
                return ResourceManager.GetString("BuyOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Buy Order Lower Limit:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BuyOrderLowerLimit {
            get {
                return ResourceManager.GetString("BuyOrderLowerLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Buy Order Price Notifications과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BuyOrderPriceNotifications {
            get {
                return ResourceManager.GetString("BuyOrderPriceNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Buy Order Upper Limit:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BuyOrderUpperLimit {
            get {
                return ResourceManager.GetString("BuyOrderUpperLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Buy Price과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BuyPrice {
            get {
                return ResourceManager.GetString("BuyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camps과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Camps {
            get {
                return ResourceManager.GetString("Camps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can Complete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CanComplete {
            get {
                return ResourceManager.GetString("CanComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cardinal Directions과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CardinalDirections {
            get {
                return ResourceManager.GetString("CardinalDirections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Castles과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Castles {
            get {
                return ResourceManager.GetString("Castles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Center on Character과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CenterOnChar {
            get {
                return ResourceManager.GetString("CenterOnChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check for Updates at Startup과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CheckForUpdatesAtStartup {
            get {
                return ResourceManager.GetString("CheckForUpdatesAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Claimed By:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ClaimedBy {
            get {
                return ResourceManager.GetString("ClaimedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Commerce과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Commerce {
            get {
                return ResourceManager.GetString("Commerce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completed Per Character과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CompletedPerChar {
            get {
                return ResourceManager.GetString("CompletedPerChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completion Options과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CompletionOptions {
            get {
                return ResourceManager.GetString("CompletionOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completion Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CompletionTime {
            get {
                return ResourceManager.GetString("CompletionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configure과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Configure {
            get {
                return ResourceManager.GetString("Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy Chat Code과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CopyChatCode {
            get {
                return ResourceManager.GetString("CopyChatCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy Enemy Headed Towards Text과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CopyEnemyHeadedTowards {
            get {
                return ResourceManager.GetString("CopyEnemyHeadedTowards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CopyName {
            get {
                return ResourceManager.GetString("CopyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy Player Headed Towards Text과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CopyPlayerHeadedTowards {
            get {
                return ResourceManager.GetString("CopyPlayerHeadedTowards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy RI Timer Text과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CopyRITimer {
            get {
                return ResourceManager.GetString("CopyRITimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy Under Attack Text과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CopyUnderAttack {
            get {
                return ResourceManager.GetString("CopyUnderAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy Waypoint Code과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CopyWaypointCode {
            get {
                return ResourceManager.GetString("CopyWaypointCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cost:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cost of 100 Gems과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CostOfGems {
            get {
                return ResourceManager.GetString("CostOfGems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Highest Buy Order:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CurrentHighestBuyOrder {
            get {
                return ResourceManager.GetString("CurrentHighestBuyOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Lowest Sell Listing:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CurrentLowestSellListing {
            get {
                return ResourceManager.GetString("CurrentLowestSellListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Zone과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CurrentZone {
            get {
                return ResourceManager.GetString("CurrentZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Custom Icon과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CustomIcon {
            get {
                return ResourceManager.GetString("CustomIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Day-Night과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DayNight {
            get {
                return ResourceManager.GetString("DayNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Day-Night Timer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DayNightTimer {
            get {
                return ResourceManager.GetString("DayNightTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete All과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DeleteAll {
            get {
                return ResourceManager.GetString("DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Description과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initial design/art input by:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DesignArtBy {
            get {
                return ResourceManager.GetString("DesignArtBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Development by:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DevelopmentBy {
            get {
                return ResourceManager.GetString("DevelopmentBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disable All과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DisableAll {
            get {
                return ResourceManager.GetString("DisableAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Distance과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Distance Units과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DistanceUnits {
            get {
                return ResourceManager.GetString("DistanceUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Don&apos;t show again과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DontShowAgain {
            get {
                return ResourceManager.GetString("DontShowAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dungeon Completion과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DungeonCompletion {
            get {
                return ResourceManager.GetString("DungeonCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paths과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DungeonPaths {
            get {
                return ResourceManager.GetString("DungeonPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dungeons과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Dungeons {
            get {
                return ResourceManager.GetString("Dungeons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dungeons Tracker과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DungeonsTracker {
            get {
                return ResourceManager.GetString("DungeonsTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dungeon Timer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DungeonTimer {
            get {
                return ResourceManager.GetString("DungeonTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ectoplasm Salvage Helper과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EctoSalvageHelper {
            get {
                return ResourceManager.GetString("EctoSalvageHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable All과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EnableAll {
            get {
                return ResourceManager.GetString("EnableAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable Logging과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EnableLogging {
            get {
                return ResourceManager.GetString("EnableLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entire Continent과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EntireContinent {
            get {
                return ResourceManager.GetString("EntireContinent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eternal Battlegrounds과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EternalBattlegrounds {
            get {
                return ResourceManager.GetString("EternalBattlegrounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show notification at this time before event begins과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EventNotificationConfigTooltip {
            get {
                return ResourceManager.GetString("EventNotificationConfigTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Event Notifications과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EventNotifications {
            get {
                return ResourceManager.GetString("EventNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Event Notification Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EventNotificationSettings {
            get {
                return ResourceManager.GetString("EventNotificationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Events과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Events Tracker과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EventsTracker {
            get {
                return ResourceManager.GetString("EventsTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Event Time Table과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EventTimeTable {
            get {
                return ResourceManager.GetString("EventTimeTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Feet과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Feet {
            get {
                return ResourceManager.GetString("Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gems To Gold Exchange과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GemsToGoldExchange {
            get {
                return ResourceManager.GetString("GemsToGoldExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click Here to Get Started과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Global과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Global {
            get {
                return ResourceManager.GetString("Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click Here to go to the Download Page과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GoToDownloadPage {
            get {
                return ResourceManager.GetString("GoToDownloadPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Green Borderlands과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GreenBorderlands {
            get {
                return ResourceManager.GetString("GreenBorderlands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Green Objectives과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GreenObjectives {
            get {
                return ResourceManager.GetString("GreenObjectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Heart Quests과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HeartQuests {
            get {
                return ResourceManager.GetString("HeartQuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hero Challenges과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HeroChallenges {
            get {
                return ResourceManager.GetString("HeroChallenges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Horizontal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Horizontal {
            get {
                return ResourceManager.GetString("Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hotkeys과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Hotkeys {
            get {
                return ResourceManager.GetString("Hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   in과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Include Location과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string IncludeLocation {
            get {
                return ResourceManager.GetString("IncludeLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid input. Try again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InvalidHotkey {
            get {
                return ResourceManager.GetString("InvalidHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP: 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string IP {
            get {
                return ResourceManager.GetString("IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Item과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Item Icon과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ItemIcon {
            get {
                return ResourceManager.GetString("ItemIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Item Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keeps과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Keeps {
            get {
                return ResourceManager.GetString("Keeps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LanguageSetting {
            get {
                return ResourceManager.GetString("LanguageSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last Active {0} ago과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LastActiveXAgo {
            get {
                return ResourceManager.GetString("LastActiveXAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Later과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Later {
            get {
                return ResourceManager.GetString("Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Length과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Listing Fee:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ListingFee {
            get {
                return ResourceManager.GetString("ListingFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Located in {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LocatedInX {
            get {
                return ResourceManager.GetString("LocatedInX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Location과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Location Options과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LocationOptions {
            get {
                return ResourceManager.GetString("LocationOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lower과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Lower {
            get {
                return ResourceManager.GetString("Lower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Map과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Map Overlay과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MapOverlay {
            get {
                return ResourceManager.GetString("MapOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maps과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Maps {
            get {
                return ResourceManager.GetString("Maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mercenary Objectives과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MercenaryObjects {
            get {
                return ResourceManager.GetString("MercenaryObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Meta Event Timers과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MetaEventTimers {
            get {
                return ResourceManager.GetString("MetaEventTimers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Meters과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Meters {
            get {
                return ResourceManager.GetString("Meters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Names과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Names {
            get {
                return ResourceManager.GetString("Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Neutral Objectives과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NeutralObjectives {
            get {
                return ResourceManager.GetString("NeutralObjectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A new version is now available!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Non-Interactive Windows과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NonInteractiveWindows {
            get {
                return ResourceManager.GetString("NonInteractiveWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Results Found과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoResultsFound {
            get {
                return ResourceManager.GetString("NoResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notes과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notifications Duration (sec)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NotificationsDuration {
            get {
                return ResourceManager.GetString("NotificationsDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Some features cannot be started because GW2 is running as administrator.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NotRunningAsAdmin {
            get {
                return ResourceManager.GetString("NotRunningAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   is now running과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NowRunning {
            get {
                return ResourceManager.GetString("NowRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Objective Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ObjectiveType {
            get {
                return ResourceManager.GetString("ObjectiveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Events Tracker과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OpenEventsTracker {
            get {
                return ResourceManager.GetString("OpenEventsTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Guide과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OpenGuide {
            get {
                return ResourceManager.GetString("OpenGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Meta Event Timers과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OpenMetaEventTimers {
            get {
                return ResourceManager.GetString("OpenMetaEventTimers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Wiki Page과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OpenWikiPage {
            get {
                return ResourceManager.GetString("OpenWikiPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open World Boss Timers과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OpenWorldBossTimers {
            get {
                return ResourceManager.GetString("OpenWorldBossTimers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open WvW Tracker과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OpenWvWTracker {
            get {
                return ResourceManager.GetString("OpenWvWTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Orientation과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Orientation {
            get {
                return ResourceManager.GetString("Orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Overlay Menu Icon과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OverlayMenuIcon {
            get {
                return ResourceManager.GetString("OverlayMenuIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Override Displayed Map과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OverrideDisplayedMap {
            get {
                return ResourceManager.GetString("OverrideDisplayedMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Owned By: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OwnedBy {
            get {
                return ResourceManager.GetString("OwnedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Owner과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Player Markers과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PlayerMarkers {
            get {
                return ResourceManager.GetString("PlayerMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Points: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   POIs과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string POIs {
            get {
                return ResourceManager.GetString("POIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Price Notifications과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PriceNotifications {
            get {
                return ResourceManager.GetString("PriceNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Price Tracker과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PriceTracker {
            get {
                return ResourceManager.GetString("PriceTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Profit {
            get {
                return ResourceManager.GetString("Profit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quantity과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rebuilding item names database...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RebuildingNamesDatabase {
            get {
                return ResourceManager.GetString("RebuildingNamesDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rebuild Item Names Database과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RebuildItemNamesDatabase {
            get {
                return ResourceManager.GetString("RebuildItemNamesDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Red Borderlands과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RedBorderlands {
            get {
                return ResourceManager.GetString("RedBorderlands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Redisplay Notifications Interval (min):과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RedisplayNotificationsIntervalMinutes {
            get {
                return ResourceManager.GetString("RedisplayNotificationsIntervalMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Red Objectives과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RedObjectives {
            get {
                return ResourceManager.GetString("RedObjectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset All과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ResetAll {
            get {
                return ResourceManager.GetString("ResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset Completed Paths과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ResetCompletedPaths {
            get {
                return ResourceManager.GetString("ResetCompletedPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset Daily과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ResetDaily {
            get {
                return ResourceManager.GetString("ResetDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset Hidden Dungeons과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ResetHiddenDungeons {
            get {
                return ResourceManager.GetString("ResetHiddenDungeons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset Hidden Events과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ResetHiddenEvents {
            get {
                return ResourceManager.GetString("ResetHiddenEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset Hidden Objectives과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ResetHiddenObjectives {
            get {
                return ResourceManager.GetString("ResetHiddenObjectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset Hidden Points과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ResetHiddenPoints {
            get {
                return ResourceManager.GetString("ResetHiddenPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset Unlocks과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ResetUnlocks {
            get {
                return ResourceManager.GetString("ResetUnlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The application must restart for the settings to be applied.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RestartApplicationInstruction {
            get {
                return ResourceManager.GetString("RestartApplicationInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Revenue:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Revenue {
            get {
                return ResourceManager.GetString("Revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reward:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Reward {
            get {
                return ResourceManager.GetString("Reward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ROI:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ROI {
            get {
                return ResourceManager.GetString("ROI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sale Fee:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SaleFee {
            get {
                return ResourceManager.GetString("SaleFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sell Listing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SellListing {
            get {
                return ResourceManager.GetString("SellListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sell Listing Lower Limit:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SellListingLowerLimit {
            get {
                return ResourceManager.GetString("SellListingLowerLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sell Listing Price Notifications과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SellListingPriceNotifications {
            get {
                return ResourceManager.GetString("SellListingPriceNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sell Listing Upper Limit:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SellListingUpperLimit {
            get {
                return ResourceManager.GetString("SellListingUpperLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sell Price과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SellPrice {
            get {
                return ResourceManager.GetString("SellPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server: 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set as Active Path과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SetActivePath {
            get {
                return ResourceManager.GetString("SetActivePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Short Names과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ShortNames {
            get {
                return ResourceManager.GetString("ShortNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show All과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Channel Box과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ShowChannelBox {
            get {
                return ResourceManager.GetString("ShowChannelBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Character Pointer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ShowCharPointer {
            get {
                return ResourceManager.GetString("ShowCharPointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Chat Entry Box과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ShowChatEntryBox {
            get {
                return ResourceManager.GetString("ShowChatEntryBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Completed Events과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ShowCompletedEvents {
            get {
                return ResourceManager.GetString("ShowCompletedEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Completed Tasks과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ShowCompletedTasks {
            get {
                return ResourceManager.GetString("ShowCompletedTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Distances과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ShowDistances {
            get {
                return ResourceManager.GetString("ShowDistances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show &quot;End of Events&quot; Notification (Restart Required)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ShowEndOfEvents {
            get {
                return ResourceManager.GetString("ShowEndOfEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Enter/Exit Channel Notifications과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ShowEnterExitChannelNotifications {
            get {
                return ResourceManager.GetString("ShowEnterExitChannelNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Gold-to-Gems Exchange과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ShowGoldToGemsExchange {
            get {
                return ResourceManager.GetString("ShowGoldToGemsExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Heart Quests과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ShowHeartQuests {
            get {
                return ResourceManager.GetString("ShowHeartQuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Hero Points과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ShowHeroPoints {
            get {
                return ResourceManager.GetString("ShowHeroPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Inactive Events과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ShowInactiveEvents {
            get {
                return ResourceManager.GetString("ShowInactiveEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show None과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ShowNone {
            get {
                return ResourceManager.GetString("ShowNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Notification Borders과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ShowNotificationBorders {
            get {
                return ResourceManager.GetString("ShowNotificationBorders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Player Markers과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ShowPlayerMarkers {
            get {
                return ResourceManager.GetString("ShowPlayerMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Points of Interest과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ShowPointsOfInterest {
            get {
                return ResourceManager.GetString("ShowPointsOfInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Tasks not on Current Map과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ShowTasksNotOnMap {
            get {
                return ResourceManager.GetString("ShowTasksNotOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Text Chat과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ShowTextChat {
            get {
                return ResourceManager.GetString("ShowTextChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Timer Value과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ShowTimerValue {
            get {
                return ResourceManager.GetString("ShowTimerValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Trail과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ShowTrail {
            get {
                return ResourceManager.GetString("ShowTrail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Unlocked Zone Points과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ShowUnlockedZonePoints {
            get {
                return ResourceManager.GetString("ShowUnlockedZonePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Vistas과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ShowVistas {
            get {
                return ResourceManager.GetString("ShowVistas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Voice Chat과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ShowVoiceChat {
            get {
                return ResourceManager.GetString("ShowVoiceChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Waypoint-Code Copy Buttons과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ShowWaypointCopyButtons {
            get {
                return ResourceManager.GetString("ShowWaypointCopyButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Waypoints과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ShowWaypoints {
            get {
                return ResourceManager.GetString("ShowWaypoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skill Challenges과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SkillChallenges {
            get {
                return ResourceManager.GetString("SkillChallenges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sort By과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Respawn Points과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SpawnPoints {
            get {
                return ResourceManager.GetString("SpawnPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Standard과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Standard {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please start Teamspeak과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StartTeamspeak {
            get {
                return ResourceManager.GetString("StartTeamspeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sticky Windows과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StickyWindows {
            get {
                return ResourceManager.GetString("StickyWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   By: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TakenBy {
            get {
                return ResourceManager.GetString("TakenBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   From: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TakenFrom {
            get {
                return ResourceManager.GetString("TakenFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tasks Tracker과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TaskTracker {
            get {
                return ResourceManager.GetString("TaskTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Teamspeak과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Teamspeak {
            get {
                return ResourceManager.GetString("Teamspeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Teamspeak Overlay과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TeamspeakOverlay {
            get {
                return ResourceManager.GetString("TeamspeakOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This application uses과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ThirdPartyLibraries {
            get {
                return ResourceManager.GetString("ThirdPartyLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time-Distances과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TimeDistances {
            get {
                return ResourceManager.GetString("TimeDistances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time until daytime과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TimeUntilDay {
            get {
                return ResourceManager.GetString("TimeUntilDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time until night과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TimeUntilNight {
            get {
                return ResourceManager.GetString("TimeUntilNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle All Windows과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToggleAllWindows {
            get {
                return ResourceManager.GetString("ToggleAllWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle Auto-Fade Window Borders과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToggleAutoFadeBorders {
            get {
                return ResourceManager.GetString("ToggleAutoFadeBorders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle Day-Night Timer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToggleDayNightTimer {
            get {
                return ResourceManager.GetString("ToggleDayNightTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle Dungeons Tracker과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToggleDungeonsTracker {
            get {
                return ResourceManager.GetString("ToggleDungeonsTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle Dungeon Timer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToggleDungeonTimer {
            get {
                return ResourceManager.GetString("ToggleDungeonTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle Events Tracker과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToggleEventsTracker {
            get {
                return ResourceManager.GetString("ToggleEventsTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle Map Overlay과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToggleMap {
            get {
                return ResourceManager.GetString("ToggleMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle Meta Event Timers과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToggleMetaEventTimers {
            get {
                return ResourceManager.GetString("ToggleMetaEventTimers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle Non-Interactive Windows과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToggleNonInteractiveWindow {
            get {
                return ResourceManager.GetString("ToggleNonInteractiveWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle Notification Window Borders과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToggleNotificationBorders {
            get {
                return ResourceManager.GetString("ToggleNotificationBorders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle Overlay Menu Icon과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToggleOverlayMenuIcon {
            get {
                return ResourceManager.GetString("ToggleOverlayMenuIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle Price Tracker과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TogglePriceTracker {
            get {
                return ResourceManager.GetString("TogglePriceTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle Tasks Tracker과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToggleTasksTracker {
            get {
                return ResourceManager.GetString("ToggleTasksTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle Teamspeak Overlay과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToggleTeamspeakOverlay {
            get {
                return ResourceManager.GetString("ToggleTeamspeakOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle Web Browser과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToggleWebBrowser {
            get {
                return ResourceManager.GetString("ToggleWebBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle World Boss Timers과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToggleWorldBossTimers {
            get {
                return ResourceManager.GetString("ToggleWorldBossTimers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle WvW Tracker과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToggleWvWTracker {
            get {
                return ResourceManager.GetString("ToggleWvWTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle Zone Completion Assistant과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToggleZoneCompletionAssistant {
            get {
                return ResourceManager.GetString("ToggleZoneCompletionAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Towers과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Towers {
            get {
                return ResourceManager.GetString("Towers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TP Calculator과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TPCalculator {
            get {
                return ResourceManager.GetString("TPCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tracked Items과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TrackedItems {
            get {
                return ResourceManager.GetString("TrackedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trail과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Trail {
            get {
                return ResourceManager.GetString("Trail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Translations By:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TranslationsBy {
            get {
                return ResourceManager.GetString("TranslationsBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upper과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Upper {
            get {
                return ResourceManager.GetString("Upper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use Player&apos;s Map과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UsePlayersMap {
            get {
                return ResourceManager.GetString("UsePlayersMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value of 100 Gems과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ValueOfGems {
            get {
                return ResourceManager.GetString("ValueOfGems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vertical과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Vertical {
            get {
                return ResourceManager.GetString("Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vistas과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Vistas {
            get {
                return ResourceManager.GetString("Vistas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Waypoint Code과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WaypointCode {
            get {
                return ResourceManager.GetString("WaypointCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Waypoints과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Waypoints {
            get {
                return ResourceManager.GetString("Waypoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Web Browser과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WebBrowser {
            get {
                return ResourceManager.GetString("WebBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   When Home World Loses Objective과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WhenHomeWorldLosesObjective {
            get {
                return ResourceManager.GetString("WhenHomeWorldLosesObjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   When Home World Takes Objective과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WhenHomeWorldTakesObjective {
            get {
                return ResourceManager.GetString("WhenHomeWorldTakesObjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   When Other World Takes Other World&apos;s Objective과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WhenOtherWorldTakesOtherWorldsObjective {
            get {
                return ResourceManager.GetString("WhenOtherWorldTakesOtherWorldsObjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Icon World_Completion2 {
            get {
                object obj = ResourceManager.GetObject("World_Completion2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   World Boss Timers과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WorldBossTimers {
            get {
                return ResourceManager.GetString("WorldBossTimers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   World Events과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WorldEvents {
            get {
                return ResourceManager.GetString("WorldEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   World Selection과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WorldSelection {
            get {
                return ResourceManager.GetString("WorldSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   World vs World과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WorldvsWorld {
            get {
                return ResourceManager.GetString("WorldvsWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enemy headed to {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WvWEnemyHeadedAltClipboardText {
            get {
                return ResourceManager.GetString("WvWEnemyHeadedAltClipboardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enemy headed to {0} ({1} {2})과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WvWEnemyHeadedClipboardText {
            get {
                return ResourceManager.GetString("WvWEnemyHeadedClipboardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} ({1} {2}) - Owned By {3} - RI: {4}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WvWGeneralClipboardText {
            get {
                return ResourceManager.GetString("WvWGeneralClipboardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} ({1} {2}) - Owned By {3} - RI is NOT active과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WvWGeneralNoRIClipboardText {
            get {
                return ResourceManager.GetString("WvWGeneralNoRIClipboardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} ({1} {2}) - RI is NOT active과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WvWNoRIClipboardText {
            get {
                return ResourceManager.GetString("WvWNoRIClipboardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WvW Notifications과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WvWNotifications {
            get {
                return ResourceManager.GetString("WvWNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I&apos;m headed to {0} - Estimated Distance: {1}{2}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WvWPlayerHeadedAltClipboardText {
            get {
                return ResourceManager.GetString("WvWPlayerHeadedAltClipboardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I&apos;m headed to {0} ({1} {2}) - Estimated Distance: {3}{4}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WvWPlayerHeadedClipboardText {
            get {
                return ResourceManager.GetString("WvWPlayerHeadedClipboardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} ({1} {2}) - RI: {3}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WvWRIClipboardText {
            get {
                return ResourceManager.GetString("WvWRIClipboardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is under attack!! ({1} {2})과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WvWUnderAttackClipboardText {
            get {
                return ResourceManager.GetString("WvWUnderAttackClipboardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zone Completion Assistant과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ZoneCompletionAssistant {
            get {
                return ResourceManager.GetString("ZoneCompletionAssistant", resourceCulture);
            }
        }
    }
}
